/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlescolar.view;

import java.awt.Color;
import mdlaf.animation.MaterialUIMovement;
import mdlaf.utils.MaterialColors;

/**
 *
 * @author hugoluna
 */
public class AdminHomeView extends javax.swing.JFrame {

    /**
     * Creates new form AdminHomeView
     */
    public AdminHomeView() {
        initComponents();
        configViews();
    }

    
    public void configViews(){
        
        containerMenu.setBackground(MaterialColors.BLUE_500);
        btnRegisterAlumn.setBackground(MaterialColors.BLUE_500);
        btnRegisterAdmin.setBackground(MaterialColors.BLUE_500);
        btnRegisterDocente.setBackground(MaterialColors.BLUE_500);
        btnRegisterMateria.setBackground(MaterialColors.BLUE_500);
        btnExit.setBackground(MaterialColors.BLUE_500);
        textRegistro.setBackground(MaterialColors.BLUE_500);
        textSearch.setBackground(MaterialColors.BLUE_500);
        
        
        /**
         * Set color ui animation button
         **/
        
        MaterialUIMovement.add(btnRegisterAlumn, MaterialColors.BLUE_400);
        MaterialUIMovement.add(btnRegisterAdmin, MaterialColors.BLUE_400);
        MaterialUIMovement.add(btnRegisterDocente, MaterialColors.BLUE_400);
        MaterialUIMovement.add(btnRegisterMateria, MaterialColors.BLUE_400);
        MaterialUIMovement.add(btnExit, MaterialColors.BLUE_400);
        
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContainer = new javax.swing.JPanel();
        containerMenu = new javax.swing.JPanel();
        btnRegisterAlumn = new javax.swing.JButton();
        textSearch = new javax.swing.JLabel();
        btnRegisterAdmin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnRegisterMateria = new javax.swing.JButton();
        btnRegisterDocente = new javax.swing.JButton();
        textRegistro = new javax.swing.JLabel();
        contenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainContainer.setBackground(new java.awt.Color(255, 255, 255));
        mainContainer.setMaximumSize(new java.awt.Dimension(1200, 700));
        mainContainer.setPreferredSize(new java.awt.Dimension(1200, 700));
        mainContainer.setSize(new java.awt.Dimension(1200, 700));

        containerMenu.setBackground(new java.awt.Color(255, 255, 255));

        btnRegisterAlumn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnRegisterAlumn.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterAlumn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlescolar/imagenes/registro.png"))); // NOI18N
        btnRegisterAlumn.setText("Alumno");
        btnRegisterAlumn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegisterAlumn.setIconTextGap(10);

        textSearch.setBackground(new java.awt.Color(255, 255, 255));
        textSearch.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        textSearch.setForeground(new java.awt.Color(255, 255, 255));
        textSearch.setText("Buscar");

        btnRegisterAdmin.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnRegisterAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlescolar/imagenes/registro.png"))); // NOI18N
        btnRegisterAdmin.setText("Administrador");
        btnRegisterAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegisterAdmin.setIconTextGap(10);

        btnExit.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Salir");

        btnRegisterMateria.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnRegisterMateria.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlescolar/imagenes/registro.png"))); // NOI18N
        btnRegisterMateria.setText("Docente");
        btnRegisterMateria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegisterMateria.setIconTextGap(10);

        btnRegisterDocente.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnRegisterDocente.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlescolar/imagenes/registro.png"))); // NOI18N
        btnRegisterDocente.setText("Docente");
        btnRegisterDocente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegisterDocente.setIconTextGap(10);

        textRegistro.setBackground(new java.awt.Color(255, 255, 255));
        textRegistro.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        textRegistro.setForeground(new java.awt.Color(255, 255, 255));
        textRegistro.setText("Registro");

        javax.swing.GroupLayout containerMenuLayout = new javax.swing.GroupLayout(containerMenu);
        containerMenu.setLayout(containerMenuLayout);
        containerMenuLayout.setHorizontalGroup(
            containerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerMenuLayout.createSequentialGroup()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(containerMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegisterAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegisterMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegisterDocente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(containerMenuLayout.createSequentialGroup()
                        .addGroup(containerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegisterAlumn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        containerMenuLayout.setVerticalGroup(
            containerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerMenuLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(textRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegisterAlumn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegisterAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegisterDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegisterMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(textSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        contenedor.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 962, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainContainerLayout = new javax.swing.GroupLayout(mainContainer);
        mainContainer.setLayout(mainContainerLayout);
        mainContainerLayout.setHorizontalGroup(
            mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContainerLayout.createSequentialGroup()
                .addComponent(containerMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainContainerLayout.setVerticalGroup(
            mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnExit;
    public javax.swing.JButton btnRegisterAdmin;
    public javax.swing.JButton btnRegisterAlumn;
    public javax.swing.JButton btnRegisterDocente;
    public javax.swing.JButton btnRegisterMateria;
    private javax.swing.JPanel containerMenu;
    public javax.swing.JPanel contenedor;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JLabel textRegistro;
    private javax.swing.JLabel textSearch;
    // End of variables declaration//GEN-END:variables
}
