/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlescolar.view;

import mdlaf.utils.MaterialColors;
import controlescolar.view.components.ImageProfile;
import java.awt.Color;
import javax.swing.border.Border;
import mdlaf.animation.MaterialUIMovement;
import mdlaf.utils.MaterialBorders;

/**
 *
 * @author hugoluna
 */
public class HomeView extends javax.swing.JFrame {

    /**
     * Creates new form HomeView
     */
    public HomeView() {
        initComponents();
        configViews();
    }

    public void configViews() {
        this.setResizable(false);
        header.setBackground(MaterialColors.BLUE_500);
        labelName.setBackground(MaterialColors.BLUE_500);
        labelNumControl.setBackground(MaterialColors.BLUE_500);
        labelIcon.setForeground(MaterialColors.BLUE_500);
        labelIcon.setBackground(Color.white);
        btnEdit.setBackground(MaterialColors.CYAN_500);
        btnEdit.setForeground(Color.white);
        MaterialUIMovement.add(btnEdit, MaterialColors.CYAN_300);
        containerBody.setBorder(MaterialBorders.LIGHT_SHADOW_BORDER);
        containerMenu.setBackground(MaterialColors.BLUE_500);
        btnHome.setBackground(MaterialColors.BLUE_500);
        btnHome.setForeground(MaterialColors.WHITE);
        btnReinscribir.setBackground(MaterialColors.BLUE_500);
        btnPayment.setBackground(MaterialColors.BLUE_500);
        btnPayment.setForeground(MaterialColors.WHITE);
        btnReinscribir.setForeground(MaterialColors.WHITE);
        btnExit.setBackground(MaterialColors.BLUE_500);
        
        
        MaterialUIMovement.add(btnHome, MaterialColors.BLUE_400);
        MaterialUIMovement.add(btnExit, MaterialColors.BLUE_400);
        MaterialUIMovement.add(btnReinscribir, MaterialColors.BLUE_400);
        MaterialUIMovement.add(btnPayment, MaterialColors.BLUE_400);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContainer = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        labelNumControl = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        labelIcon = new javax.swing.JLabel();
        containerMenu = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnReinscribir = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnPayment = new javax.swing.JButton();
        containerBody = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 700));

        mainContainer.setBackground(new java.awt.Color(255, 255, 255));
        mainContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelName.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        labelName.setForeground(new java.awt.Color(255, 255, 255));
        labelName.setText("Nombre del alumno");

        labelNumControl.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelNumControl.setForeground(new java.awt.Color(255, 255, 255));
        labelNumControl.setText("Numero de control");

        btnEdit.setText("EDITAR PERFIL");

        labelIcon.setBackground(new java.awt.Color(255, 255, 255));
        labelIcon.setFont(new java.awt.Font("Lucida Grande", 0, 80)); // NOI18N
        labelIcon.setForeground(new java.awt.Color(255, 255, 255));
        labelIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIcon.setText("HL");
        labelIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(labelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNumControl, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(548, Short.MAX_VALUE))))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNumControl)
                .addGap(21, 21, 21)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        mainContainer.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        containerMenu.setBackground(new java.awt.Color(255, 255, 255));

        btnHome.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlescolar/imagenes/casa.png"))); // NOI18N
        btnHome.setText("Inicio");
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnHome.setIconTextGap(10);
        btnHome.setMargin(new java.awt.Insets(0, 25, 0, 2));

        btnReinscribir.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnReinscribir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlescolar/imagenes/cepillado.png"))); // NOI18N
        btnReinscribir.setText("Reinscribir");
        btnReinscribir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReinscribir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnReinscribir.setIconTextGap(10);
        btnReinscribir.setMargin(new java.awt.Insets(0, 25, 0, 2));

        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Salir");

        btnPayment.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlescolar/imagenes/bolso.png"))); // NOI18N
        btnPayment.setText("Pagos");
        btnPayment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPayment.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPayment.setIconTextGap(10);
        btnPayment.setMargin(new java.awt.Insets(0, 25, 0, 2));

        javax.swing.GroupLayout containerMenuLayout = new javax.swing.GroupLayout(containerMenu);
        containerMenu.setLayout(containerMenuLayout);
        containerMenuLayout.setHorizontalGroup(
            containerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
            .addComponent(btnReinscribir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(containerMenuLayout.createSequentialGroup()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(btnPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        containerMenuLayout.setVerticalGroup(
            containerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerMenuLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReinscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainContainer.add(containerMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 240, 510));

        javax.swing.GroupLayout containerBodyLayout = new javax.swing.GroupLayout(containerBody);
        containerBody.setLayout(containerBodyLayout);
        containerBodyLayout.setHorizontalGroup(
            containerBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        containerBodyLayout.setVerticalGroup(
            containerBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        mainContainer.add(containerBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 940, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEdit;
    public javax.swing.JButton btnExit;
    public javax.swing.JButton btnHome;
    public javax.swing.JButton btnPayment;
    public javax.swing.JButton btnReinscribir;
    public javax.swing.JPanel containerBody;
    private javax.swing.JPanel containerMenu;
    private javax.swing.JPanel header;
    public javax.swing.JLabel labelIcon;
    public javax.swing.JLabel labelName;
    public javax.swing.JLabel labelNumControl;
    public javax.swing.JPanel mainContainer;
    // End of variables declaration//GEN-END:variables
}
